### ISSUE TITLE
Developing Against Kubernetes with Skaffold

### ISSUE THREAD

**Issue by rawkode** [rawkode/live#11]

**Comment by tstromberg** [comment]
Skaffold is one of the tools my team works on, so please let me know if you would like introductions to the folks behind them. I bet one of them would be more than happy to be on your show:

@bdealwis
@gsquared94
@marlongamez
@nkubala
@tejal29

**Comment by rawkode** [comment]
I'd love to get this scheduled. If one of you would like to comment, we can move to email and find a suitable date and time 😀

**Comment by viglesiasce** [comment]
Hey @rawkode! 

I'm the PM for Skaffold.

I'd love to help out with whatever you need for this episode including getting the right folks lined up or content scoped out.
