### ISSUE TITLE
Use Case : Secrets in multi k8s-environments

### ISSUE THREAD

**Issue by philwelz** [rawkode/live#13]
Level: Use Case 

Why: 

Use case how you would use secrets in a multi cloud, multi on-prem cluster or multi environment setup.

- Should you use HashiCorp Vault ? Or Sealed Secrets? Or is there something better?
- Should Secrets be handled at application or Pod level? 
- How pull secrets for images can be handled? 
- What about secrets in Variables (for example in GitLab)?

**Comment by phroggyy** [comment]
I'm very interested in this one, in particular managing environment variables for staging/prod (how can we do it with sealed-secrets vs vault vs regular secrets?), which ties in with the "secrets in variables" point.

Could we consider a mini-series with one option per episode, specifically looking at handling multiple environments with different values, optionally with a compare & contrast to end?

Not sure if my idea strays too far from the original one and should have its own issue.
